### PR TITLE
Adds support for bulk values

### PR DESCRIPTION
**Pull request by rburness**
Adds support for bulk values for inserts

### CODE REVIEW

**Comment by chrisbarber86** [comment]
@rburness can  you bump the lib/version.rb file to the next version so we can make a cut straight after merging this?

**Comment by adamgeorgeson** [comment]
I always forget that! @chrisbarber86

**Comment by rburness** [comment]
@adamgeorgeson @chrisbarber86 it's worth mentioning now that we may need to make another change to add support for `bulk_set` for bulk updates. I didn't include it in this PR as i'm yet to look into it. Do you have any preference on whether or not i look into it now and add it to this PR or look into it when i come to tackle the work and then raise another PR/version? Cheers.

**Comment by chrisbarber86** [comment]
@rburness just raise a separate PR and we'll do minor version bump

**Pull request merged**
